/**
 * Payment Provider Interface
 *
 * Abstraction for payment processors (Paystack, Flutterwave, etc.)
 * Domain logic must not depend on specific provider implementations.
 */

export interface InitializePaymentParams {
  /**
   * Unique reference generated by our system (not Paystack's)
   * This is our primary defense against double-processing
   */
  reference: string;

  /**
   * Amount in kobo (₦1 = 100 kobo)
   * Always integer, never float
   */
  amountKobo: number;

  /**
   * Guest's email (optional, for receipt)
   */
  email?: string;

  /**
   * Callback URL after checkout
   */
  callbackUrl?: string;

  /**
   * Metadata to attach to the transaction
   */
  metadata?: Record<string, any>;
}

export interface PaymentInitResult {
  /**
   * URL to redirect guest to for checkout
   * This is the provider's hosted payment page
   */
  authorizationUrl: string;

  /**
   * Access code for the payment session
   */
  accessCode: string;

  /**
   * Our reference echoed back
   */
  reference: string;
}

export interface PaymentVerification {
  /**
   * Payment reference
   */
  reference: string;

  /**
   * Final payment status
   */
  status: 'success' | 'failed' | 'abandoned' | 'pending';

  /**
   * Amount actually paid in kobo
   * MUST match what we initialized with
   */
  amountKobo: number;

  /**
   * Provider's transaction reference
   */
  /**
   * ISO currency code as reported by the provider (e.g. "NGN").
   * Settlement rejects anything that isn't what we charged in.
   */
  currency?: string;

  /**
   * Processing fee the provider deducted, in kobo (informational; see
   * reconciliation notes on how fees surface as drift).
   */
  feesKobo?: number;

  providerReference?: string;

  /**
   * When the payment was completed
   */
  paidAt?: Date;

  /**
   * Raw provider response for debugging
   */
  raw?: any;
}

/**
 * Payment Provider Interface
 *
 * All payment processors must implement this interface.
 * First implementation: PaystackProvider
 */
/**
 * DI token for the active PaymentProvider. Domain code injects this token,
 * never a concrete provider class.
 */
export const PAYMENT_PROVIDER = Symbol('PAYMENT_PROVIDER');

export interface PaymentProvider {
  /** Stable identifier stored on PaymentTransaction.provider (e.g. "paystack"). */
  readonly name: string;

  /**
   * Initialize a payment and get checkout URL
   * Guest will be redirected to this URL to complete payment
   *
   * NEVER build a custom card form - always use provider's hosted page
   */
  initializePayment(params: InitializePaymentParams): Promise<PaymentInitResult>;

  /**
   * Verify a payment directly against provider's API
   * This is the fallback when webhook hasn't fired yet
   *
   * DO NOT trust client-side redirect as proof of payment
   */
  verifyPayment(reference: string): Promise<PaymentVerification>;

  /**
   * Verify webhook signature to ensure it came from the provider
   *
   * MUST be called before processing any webhook payload
   * Reject any payload with invalid signature
   */
  verifyWebhookSignature(payload: Buffer, signature: string): boolean;
}
